# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categories',
            new_name='subcategories',
        ),
        migrations.AlterField(
            model_name='event',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='wished_by',
            field=models.ManyToManyField(blank=True, related_name='wishlist_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='wished_by',
            field=models.ManyToManyField(blank=True, related_name='wishlist_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
